apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-placeManage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub-placeManage
  template:
    metadata:
      labels:
        app: pub-placeManage
    spec:
      containers:
        - image: datowl/placeManageSerivce
          name: pub-placeManage
          ports:
            - containerPort: 8083
              name: pub-placeManage
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.0.101:5433/"
            - name: POSTGRES_PASSWORD
              value: "1322"
            - name: POSTGRES_USERNAME
              value: "postgres"